name: Bump formulae and casks on schedule or request

on:
  workflow_dispatch:
    inputs:
      targets:
        description: Custom list of formulae/casks to livecheck and bump if outdated
        required: false
  schedule:
    # Daily at 08:23 UTC+8
    - cron: "23 0 * * *"

permissions:
  contents: write

jobs:
  bump:
    env:
      HOMEBREW_DEVELOPER: 1
    runs-on: macos-latest
    steps:
      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@main
        with:
          core: true
          cask: true

      - name: Bump formulae and casks
        id: bump
        env:
          HOMEBREW_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TARGETS: ${{ inputs.targets }}
        continue-on-error: true
        run: |
          BREW_BUMP=(brew bump)
          if [[ -n "${TARGETS-}" ]]; then
            xargs "${BREW_BUMP[@]}" <<<"${TARGETS}"
          else
            "${BREW_BUMP[@]}" --auto --tap=rileychh/tap
          fi
